/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { NFTMinimal, NFTMinimalInterface } from "../NFTMinimal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "ApprovalForAll",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class NFTMinimal__factory {
  static readonly abi = _abi;
  static createInterface(): NFTMinimalInterface {
    return new utils.Interface(_abi) as NFTMinimalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NFTMinimal {
    return new Contract(address, _abi, signerOrProvider) as NFTMinimal;
  }
}
