version: '3.8'
services:
  backend:
    build: .
    volumes:
      - .:/app
      - ./app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: yarn start:prod
    env_file:
      - .env
