version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
  backend:
    build: .
    volumes:
      - .:/app
      - ./app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: yarn start:prod
    env_file:
      - .env
    depends_on:
      - mongodb
volumes:
  database:
